import GlobalProvider from "@/components/Application/GlobalProvider";
import "./globals.css";
import { Inter, Playfair_Display } from 'next/font/google'
import { ToastContainer } from 'react-toastify';
const interFont = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-geist-sans'
})

const playfairFont = Playfair_Display({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} ${playfairFont.variable} font-sans antialiased`}
      >
        <GlobalProvider>
          <ToastContainer />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
